src/Events.Functions/SubscriptionValidation.cs

Include valid cloud event in subscription validation

---

src/Events/Services/SubscriptionService.cs
test/Altinn.Platform.Events.Tests/Data/subscriptions/1.json
test/Altinn.Platform.Events.Tests/TestingServices/SubscriptionServiceTest.cs

The subscription source filter will now only match if the URL path
segments match, instead of comparing two URLs as strings.
Example:
Filter: https://host.com/a/b
will no longer match events with source: https://host.com/a/bc
but will still match with: https://host.com/a/b/instance/1
- #25

Feature/25 fix subscription source filter to match on URL path segments

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj

V 6.23.1 of the package causes function to fail during token generation. Must investigate cause of error and request fix from microsoft before patching this library. 
N/A

roll back Microsoft.IdentityModel.Tokens to 6.23.0

---

src/Events/Repository/SubscriptionRepository.cs

When adding the property Validated to Subscription I forgot to ensure the property were set when reading from the result set after DB call.
- #129

Transfer validated value into subscription object

---

renovate.json

Freeze Microsoft.IdentityModel.Tokens at version 6.23.0 until we have confirmed that newer versions don't break.
- #153

Block Microsoft.IdentityModel.Tokens in renovate

---

src/Events/Controllers/AppEventsController.cs
test/Altinn.Platform.Events.Tests/TestingControllers/AppEventsControllerTests.cs

- Validating DateTime-objects in controller to avoid exception being thrown by database.
- Moved validation of common query parameters to a private method that throws an exception. Could be middleware instead or set up as a Guard I guess. Open for suggestions here to avoid duplication of the validation logic. 
- #28

Check for dateTime.Kind specified in query params

---

.github/labeler.yml
.github/workflows/pr-labeler.yml

Added workflow to label prs that modify the migration scripts
Given pull_request_target context, workflow must be merged before it can be tested. 
Also given the limited scope of the workflow, and us being required to approve changes to the workflow, 
I believe we can move forward with using pull_request_target as the context although it is not reccomended for more extensive workflows. 
- Altinn/altinn-platform#222

added labeler workflow

---

src/Events.Functions/Clients/EventsClient.cs

Duplicate constructor causes problems with dependency injection.

Removed duplicate constructor

---

src/Events.Functions/Clients/EventsClient.cs
src/Events/Altinn.Platform.Events.csproj
src/Events/Clients/EventsQueueClient.cs
src/Events/Clients/Interfaces/IEventsQueueClient.cs
src/Events/Configuration/QueueStorageSettings.cs
src/Events/Controllers/AppController.cs
src/Events/Migration/v0.15/01-setup-functions.sql
src/Events/Repository/CloudEventRepository.cs
src/Events/Services/EventsService.cs
src/Events/Services/Interfaces/IEventsService.cs
src/Events/appsettings.json
test/Altinn.Platform.Events.Tests/Mocks/CloudEventRepositoryMock.cs
test/Altinn.Platform.Events.Tests/Mocks/EventsQueueClientMock.cs
test/Altinn.Platform.Events.Tests/Mocks/EventsServiceMock.cs
test/Altinn.Platform.Events.Tests/TestingControllers/AppControllerTests.cs
test/Altinn.Platform.Events.Tests/TestingServices/EventsServiceTest.cs

Activate usage of events-registration queue for incoming cloud events.
Infrastructure for processing events in `events-registration` queue has been tested and verified. This PR makes the new flow active for all new events.
- #124 
- #112

Store incoming cloud events in events-registration queue

---

src/Events/Migration/v0.17/01-setup-functions.sql
src/Events/Repository/CloudEventRepository.cs

"cloudevent" is no longer an INOUT param so must use PROCEDURE instead of FUNCTION.

SQL: FUNCTION with no OUT params must be PROCEDURE

---

src/Events/Migration/v0.17/01-setup-functions.sql

Can not change existing function to procedure, must drop first.

Drop function before creating PROC with same name and signature

---

src/Events/Controllers/InboundController.cs
src/Events/Controllers/OutboundController.cs
src/Events/Controllers/PushController.cs
src/Events/Controllers/StorageController.cs

Add a "Private API" description to the tags of internal API endpoints.
Makes it easier to not confuse them with the public available endpoints in the Swagger documentation.
PR for docs: https://github.com/Altinn/altinn-studio-docs/pull/762
Produces the following change to the OpenAPI specification
```json
"tags": [
{
"name": "Inbound",
"description": "Private API"
},
{
"name": "Outbound",
"description": "Private API"
},
{
"name": "Push",
"description": "Private API"
},
{
"name": "Storage",
"description": "Private API"
}
]
```
- just a minor tweak.

Create Swagger tag description for private API endpoints

---

src/Events.Functions/Clients/EventsClient.cs
test/Altinn.Platform.Events.Functions.Tests/TestingClients/EventsClientTests.cs

no longer throwing exception in eventsClient  if validate subscription returns 404. Simply logging error and returning. 
Goal is to not retry validation for subscriptions we cannot find in the database.
- #250

not throwing exception of 404 respnse to validate

---

.github/workflows/use-case-ATX.yaml
test/k6/src/tests/events/get.js

Use case tests for AT have been failing for quite some time due to bad testdata, but workflow has been running green. Fixed issue in test where serialization issue stopped the error from being registered in the k6 results.
- N/A

Workflow not failing if k6 fails

---

src/Events/Migration/v0.28/01-alter-function.sql

- Ensuring last 30 secs of events are not returned to ensure all transactions have completed. Goes for both getappevents and getevents functions.  
- GetAppEvents function will not return cloudevents where _time_ is not defined in the cloud event. As controller ensures this is set it should not be an issue.
- #244

not including latest 30 sec of events

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj

Revert removal of dependency to JWTCookieAuthentication. 
Remove direct dependency to Microsoft.IdentityModel.Tokens. This is included through JWTCookieAuthentication and was causing version issues.

Revert removal of dependency to JWTCookieAuthentication

---

test/k6/src/tests/subscriptions.js

Test is flaky when confirming that the subscription has been validated ok. 
Removing this for now until we have a stable webhook to use for use case tests for subscription

removed flaky test for validated subs

---

src/Events/Migration/v0.32/01-new-indexes.sql
src/Events/Migration/v0.32/01-new-indices.sql
src/Events/Migration/v0.32/02-update-function.sql

This adds B-tree indices for queryable JSON columns and, adjusts function for improved query performance on generic events. 
The GIN index employed does not support  `cloudevent ->> 'id = ...` WHERE clauses, causing the `getevents` function to do sequential scans. This change:
* Drops the GIN index and adds B-tree indices for the columns that can be used for filtering.
* Replaces ILIKE with LIKE on the source-column, which helps index performance when querying (~20%). 
* Changes `VOLATILE PARALLEL UNSAFE` to `STABLE PARALLEL SAFE` to hint to Postgre that this is a pure function
Tests performed locally on 1.000.000 rows increases performance by an order of magnitude:
```sql
-- The table has 1.000.000 randomized entries, with a UUID after '/dialogs/', 
-- so a match for '/ab%' here will hit …
```

Increase query performance on GET

---

src/Events/Services/AppSubscriptionService.cs
test/Altinn.Platform.Events.Tests/TestingServices/AppSubscriptionServiceTest.cs

Null value handling in app subscription servce. Not assuming that sourcefilter isn't null
- N/A

null handling for sourcefilter in validation

---

src/Events/Configuration/AuthorizationConstants.cs
src/Events/Extensions/ClaimsPrincipalExtensions.cs
src/Events/Services/AuthorizationService.cs
test/Altinn.Platform.Events.Tests/TestingServices/AuthorizationServiceTest.cs
test/Altinn.Platform.Events.Tests/TestingServices/OutboundServiceTests.cs
test/Altinn.Platform.Events.Tests/Utils/PrincipalUtil.cs

This adds a way to authorize publishing of all event types if a special scope is provided in addition to the ordinary authorization policy.
This adds a short circuit in the AuthorizationService, checking if the authenticated and authorized principal has supplied a scope-claim containing the `altinn:events.publish.admin`, which will the cause the HTTP request to PEP to be omitted. This will be used by Dialogporten when producing events on behalf of service owners on with arbitrary `resource`-properties. This avoids having to add a rule in all XACMLs for "publish" to Digdir, and avoids the external HTTP requests against Authorization which should help performance.
This also fixes `HasRequiredScope(this ClaimsPrincipal user, string requiredScope)` so that it splits on space and uses `Equals` …

Add administrative publishing scope short circuiting authorization

---

src/Events/Altinn.Platform.Events.csproj

Bumping the AspNetCore.HealthChecks.NpgSql is now the probable cause of crash loop in events. Revering the bump.
- Patching

Revert bumping of AspNetCore.HealthChecks.NpgSql

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
src/Events/Altinn.Platform.Events.csproj

This change is upgrading the AccessToken libraries to the latest preview. This is primarily to test the packages in dotnet 7 and dotnet 6 projects.
- https://github.com/Altinn/altinn-accesstoken/issues/74

Testing the latest preview version of the AccessToken libraries.

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj

There is an unnecessary dependency on JWTCookieAuthentication in the Events Function project. The dependency can be replaced with a dependency to Microsoft.Extensions.Http instead.
- https://github.com/Altinn/altinn-accesstoken/issues/74

Remove JWTCookieAuthentication dependency

---

src/Events/Controllers/SubscriptionController.cs

IN some cases subscription controller can respond with 500. To make debugging these cases easier we persist the subscription request with all input parameters in these cases. 
- N/A

Persist request body in telemetry if request results in error response 

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj

We're not ready to update AccessTokenClient in functions yet.

Revert dep. AccessTokenClient back to 1.1.3

---

src/Events/Migration/v0.19/01-setup-cron-job.sql
src/Events/Migration/v0.21/03-setup-cron-job.sql

Avoid referencing pg_cron when running locally

Avoid referencing pg_cron when running locally

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj

Reverting the AccessTokenClient to 1.1.3
Reverting the AccessTokenClient to 1.1.3
- #528

#528 Reverting the AccessTokenClient to 1.1.3

---

src/Events/Authorization/AppCloudEventXacmlMapper.cs
src/Events/Authorization/GenericCloudEventXacmlMapper.cs
src/Events/Authorization/SubscriptionXacmlMapper.cs
src/Events/Authorization/XacmlMapperHelper.cs
test/Altinn.Platform.Events.Tests/TestingUtils/XacmlMapperHelperTests.cs

- For both generic and app events, if a subject filter is included the subject value is included as a part of the resource definition in the decision request. 
- Extension methods for adding attributes to a XacmlJsonCategory one specifically for urns, does not analyze the contents in any way and one specified on subject which supports both urn and known formsats such as /user/1234 and /organisation/23456
- #520

subject attributes included in resource for decision request

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj

It's about time to find out in more detail why it fails when updating AccessTokenClient.

Bump dependencies

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj

Downgrade the Altinn.Common.AccessTokenClient to 1.1.3
- None

Downgrade the Altinn.Common.AccessTokenClient

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj

Revert Altinn.Common.AccessTokenClient version to 1.1.3

Revert Altinn.Common.AccessTokenClient version to 1.1.3

---

test/Postman/Events.postman_collection.json

I believe I have verified that the webhook is no longer valid. 
In Postman, I performed a POST to the webhook URL with a simple {"text" : ".."} json payload. The result was 403 Forbidden, "invalid_token". 
- #608

Replace hardcoded webook URL with var in Events.postman_collection.json

---

.github/workflows/build-and-analyze.yml

- Remove the superfluous caching of Sonar packages in the build pipeline
- Add the build workflow's path as a PR trigger for itself, so that it gets triggered for PRs that modify it
[#153](https://github.com/Altinn/team-core-private/issues/153) (team-core-private)

Remove superfluous Sonar cache step from build workflow

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
src/Events/Altinn.Platform.Events.csproj

Manually updating the outdated dependencies because renovate tried to update the package `Altinn.Common.AccessTokenClient` at the same time.

Update a set of dependencies

---

src/Events/Controllers/SubscriptionController.cs
src/Events/Services/SubscriptionService.cs
test/Altinn.Platform.Events.Tests/TestingControllers/SubscriptionControllerTests.cs
test/Altinn.Platform.Events.Tests/TestingServices/SubscriptionServiceTest.cs

Returning error code 403 Forbidden when the provided identity does not match the identity with access to a resource
- #627

627 Should return Forbidden when subscribing to a resource without access

---

src/Events/appsettings.Production.json

Apparently, neither "ApplicationInsights" nor "OpenTelemetry" works as logging provider in our current setup. Until we find another way of targeting OTel/AppInsights directly, we will default to `Warning` in Production, [as in Storage](https://github.com/Altinn/altinn-storage/pull/660/files)
- [#136 (team-core-private)](https://github.com/orgs/Altinn/projects/20/views/11?pane=issue&itemId=94396448&issue=Altinn%7Cteam-core-private%7C136)

Default to 'Warning' log filters in prod

---

src/Events.Functions/Altinn.Platform.Events.Functions.csproj

Change Events.Functions pacakge reference to specific version of AccessTokenClient
By using square brackets enclosing the version reference of a package in a project file, the package won't be updated.
https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#version-ranges

Change Events.Functions package reference to specific version

---

src/Events.Functions/Clients/EventsClient.cs
src/Events/Services/TraceLogService.cs

In certain cases where activity should have been 'outboundQueue', the value was overridden and set to 'unauthorized'.
- #658

Fix hard-coded activity value when creating subscription detail logs
