src/Events.Functions/Altinn.Platform.Events.Functions.csproj, src/Events.Functions/EventsInbound.cs, src/Events.Functions/EventsOutbound.cs, src/Events.Functions/Extensions/HttpClientExtension.cs, src/Events.Functions/Models/CloudEvent.cs, src/Events.Functions/Models/Payloads/SlackEnvelope.cs, src/Events.Functions/Models/Subscription.cs, src/Events.Functions/Services/KeyVaultService.cs, src/Events.Functions/Services/PushEventsService.cs, src/Events.Functions/Services/WebhookService.cs, src/Events.Functions/SubscriptionValidation.cs
- Fixed warnings and messages
- Bumped to .net 6
- Bumpet functions to .net 4
- altinn/altinn-studio#7554
=> Upgrade functions to v4 and .net 6

src/Events/Altinn.Platform.Events.csproj, src/Events/Controllers/EventsController.cs, src/Events/Controllers/SubscriptionController.cs, src/Events/Mappers/CloudEventMapper.cs, src/Events/Mappers/SubscriptionMapper.cs, src/Events/Models/CloudEventRequestModel.cs, src/Events/Models/Subscription.cs, src/Events/Models/SubscriptionRequestModel.cs, src/Events/Program.cs, src/Events/Swagger/RequestBodyExampleFilter.cs, src/Events/Swagger/SchemaExampleFilter.cs, test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingControllers/SubscriptionControllerTests.cs
- Using seperate models for POST requests
- Added AutoMapper
- Added classes for providing examples for schemas and requestbodies 
- Added authorization for swagger
- Altinn/altinn-platform#103
=> Modifications for better Swagger doc

src/Events/Controllers/SubscriptionController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/SubscriptionControllerTests.cs
Validating sourceFilter as an absolute uri before retrievering the absolute uri 
- #2
=> Validating subscription source filter

src/Events/Controllers/SubscriptionController.cs, src/Events/Models/SubscriptionList.cs, src/Events/Services/Interfaces/ISubscriptionService.cs, src/Events/Services/SubscriptionService.cs, src/Events/Swagger/SchemaExampleFilter.cs, test/Altinn.Platform.Events.Tests/Mocks/SubscriptionRepositoryMock.cs, test/Altinn.Platform.Events.Tests/TestingControllers/SubscriptionControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingServices/SubscriptionServiceTest.cs
Added endpoint for users to retrieve all their subscriptions. 
- #1
=> Endpoint for retrieving all subscriptions

src/Events/Migration/v0.10/01-setup-functions.sql, src/Events/Repository/ISubscriptionRepository.cs, src/Events/Repository/SubscriptionRepository.cs, src/Events/Services/SubscriptionService.cs, test/Altinn.Platform.Events.Tests/Mocks/SubscriptionRepositoryMock.cs, test/Altinn.Platform.Events.Tests/TestingServices/SubscriptionServiceTest.cs
=> enable filtering of valid state on getSubscription function

.github/workflows/build-and-analyze.yml, src/Events/Repository/CloudEventRepository.cs, src/Events/Repository/SubscriptionRepository.cs
Update db-call to run async.
See documentation:
https://www.npgsql.org/doc/basic-usage.html
=> Changed behaviour for get cloudevent

src/Events/Migration/v0.11/01-setup-functions.sql, src/Events/Repository/CloudEventRepository.cs
=> send size as input to get function

src/Events/Migration/v0.12/01-setup-index.sql
Add a new index for the id column in order to improve the performance of queries using the id as a filter.
=> Add index for id column in events.events table

Dockerfile
Description
Weekly update of container images used when building Events
=> Update base images for .Net SDK and Runtime

src/Events/Controllers/EventsController.cs, src/Events/Controllers/SubscriptionController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs
=> Returning problem details for all bad requests

src/Events/Controllers/EventsController.cs
Events controller serialized the exception in the response message. Should not expose the inner workings to the client. Removed the exception. 
- #N/A
=> removed exception from output

src/Events/Controllers/EventsController.cs, src/Events/Swagger/RequestBodyExampleFilter.cs, test/Altinn.Platform.Events.Tests/Mocks/EventsServiceMock.cs, test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs
- Added new test: GetForParty_WildcardApp_ReturnsOk
- #98
=> Add test for get events with wildcard source

src/Events/Controllers/AppEventsController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/AppEventsControllerTests.cs
=> Change name for eventscontroller

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
Downgrade patching causing issues
- N/A
=> downgrade dep

.github/workflows/build-and-analyze.yml
Split workflow into more granular steps to track the duration of test step
- N/A
=> split test in seperate step

src/Events/Controllers/AppEventsController.cs, src/Events/Services/AppEventsService.cs, test/Altinn.Platform.Events.Tests/TestingServices/AppEventsServiceTest.cs
=> added missig check in appeventsservice

src/Events/Migration/v0.15/01-drop-function.sql
Droping unused function 
- #N/A
=> alter and drop getsubscriptionsbyconsumer

src/Events/Migration/v0.15/01-drop-function.sql
events_admin does not have right to alter table ownership either rolling back migration. Must wait untill altinn/altinn-platform#286
- N/A
=> deleted migration 0.15

src/Events/Controllers/StorageController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/StorageControllerTests.cs
Bug in Storage controller, additional authorize also requiring bearer token. 
- #112
=> removed double authotrization tag

src/Events.Functions/Clients/EventsClient.cs, src/Events/Controllers/StorageController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/StorageControllerTests.cs
Adjust EventsClient to call POST instead of PUT on /inbound endpoint
- #112
=> Fix http codes, verbs

src/Events/Repository/CloudEventRepository.cs
Return OUTPUT parameter by name
- #118
=> Fix parameter index (use name instead)

src/Events/Altinn.Platform.Events.csproj, src/Events/Program.cs
=> replaces deprecated dependencies related to identity and key vault

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
This package is causing issues for upgrading other packages. Attempting to upgrade this again to see if the error message has changed. 
- #153
=> upgraded Microsoft.IdentityModel.Tokens

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
=> Patched function app for w45

.github/workflows/build-and-analyze.yml
Quality gate in SonarCloud is currently failing due to duplication of code in migration scripts. 
As this is not a sentral part of the source code that we want to analyse for code quality, I've excluded the migration scripts from the evaluation of code coverage
=> added migration/ to sonar.cpd.exclusions

.github/workflows/build-and-analyze.yml
Exclude migration script from code coverage analysis
=> exclude migration script from code coverage

src/Events.Functions/Factories/CustomQueueProcessorFactory.cs, src/Events/Configuration/PostgreSQLSettings.cs, src/Events/Controllers/StorageController.cs, src/Events/Program.cs, src/Events/Repository/CloudEventRepository.cs, src/Events/Repository/SubscriptionRepository.cs
=> fixed code smells from SonarCloud

src/Events.Functions/Clients/EventsClient.cs
=> using outbound endpoint instead of push

src/Events/Migration/v0.22/01-cleanup-obsolete.sql
Clean up unused functions and procedures now that we are fully deployed to flexible server.
See #226
=> Remove unused functions and procedures

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
=> patched accesstokenclient

src/Events/Controllers/EventsController.cs, src/Events/Controllers/InboundController.cs, src/Events/Controllers/StorageController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingControllers/InboundControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingControllers/StorageControllerTests.cs
events.subject is optional. Returning 200 instead of 201 for all internal endpoints as well as post for events controller.
- #103
=> 201 -> 200

src/Events/Controllers/InboundController.cs, src/Events/Controllers/OutboundController.cs, src/Events/Controllers/StorageController.cs, src/Events/Services/OutboundService.cs, test/Altinn.Platform.Events.Tests/TestingServices/OutboundServiceTests.cs
=> Add logging to controllers

test/k6/.gitignore, test/k6/docker-compose.yml, test/k6/readme.md, test/k6/src/api/events.js, test/k6/src/api/token-generator.js, test/k6/src/config.js, test/k6/src/data/event.json, test/k6/src/errorhandler.js, test/k6/src/report.js, test/k6/src/reports/readme.md, test/k6/src/setup.js, test/k6/src/tests/events.js
Happy path tests for POST events/api/v1/events endpoint implemented
Structure for k6 test project is also set up. Feedback is highly appreciated 
- #103
=> added first k6 test

src/Events.Functions/Altinn.Platform.Events.Functions.csproj, src/Events.Functions/Factories/CustomQueueProcessorFactory.cs, src/Events.Functions/Factories/QueueProcessorWrapper.cs
=> added wrapper quque processor + patching

src/Events/Migration/v0.23/03-setup-function.sql
Bug in migration script v0.23
- #96
=> specify language in function scripts

src/Events/Altinn.Platform.Events.csproj, src/Events/Configuration/AuthorizationConstants.cs, src/Events/Controllers/SubscriptionController.cs, src/Events/Extensions/ClaimsPrincipalExtensions.cs, src/Events/Models/SubscriptionRequestModel.cs, src/Events/Program.cs, src/Events/Services/AppSubscriptionService.cs, src/Events/Services/GenericSubscriptionService.cs, src/Events/Services/Interfaces/IAppSubscriptionService.cs, src/Events/Services/Interfaces/IGenericSubscriptionService.cs, src/Events/Services/Interfaces/ISubscriptionService.cs, src/Events/Services/SubscriptionService.cs, test/Altinn.Platform.Events.Tests/TestingControllers/SubscriptionControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingServices/AppSubscriptionServiceTest.cs, test/Altinn.Platform.Events.Tests/TestingServices/GenericSubscriptionServiceTest.cs, test/Altinn.Platform.Events.Tests/TestingServices/SubscriptionServiceTest.cs
=> controller supporting generic subscriptions

src/Events/Models/SubscriptionRequestModel.cs, src/Events/Services/AppSubscriptionService.cs, src/Events/Services/GenericSubscriptionService.cs, src/Events/Services/SubscriptionService.cs, test/Altinn.Platform.Events.Tests/TestingServices/AppSubscriptionServiceTest.cs, test/Altinn.Platform.Events.Tests/TestingServices/GenericSubscriptionServiceTest.cs, test/Altinn.Platform.Events.Tests/TestingServices/SubscriptionServiceTest.cs, test/Altinn.Platform.Events.Tests/Utils/PrincipalUtil.cs
=> Consumer of subscription always set by system

src/Events/Extensions/UriExtensions.cs, src/Events/Services/GenericSubscriptionService.cs, test/Altinn.Platform.Events.Tests/TestingExtensions/UriExtensionsTests.cs, test/Altinn.Platform.Events.Tests/TestingServices/GenericSubscriptionServiceTest.cs
=> added validation for urn for generic subscriptions

src/Events/Controllers/SubscriptionController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/SubscriptionControllerTests.cs
=> added validation of missing subscription endpoint

src/Events/Migration/v0.24/01-cleanup-obsolete.sql
=> dropping obsolete functions in v0.24 of db migration

src/Events/Extensions/UriExtensions.cs, test/Altinn.Platform.Events.Tests/TestingExtensions/UriExtensionsTests.cs, test/Altinn.Platform.Events.Tests/TestingServices/GenericSubscriptionServiceTest.cs
=> Handle source urls the same, regardless of trailing '/'

src/Events/Altinn.Platform.Events.csproj, src/Events/Program.cs, src/Events/Properties/launchSettings.json, src/Events/Services/Interfaces/IRegisterService.cs, src/Events/Services/ProfileService.cs, src/Events/Services/RegisterService.cs, test/Altinn.Platform.Events.Tests/TestingServices/ProfileServiceTest.cs, test/Altinn.Platform.Events.Tests/TestingServices/RegisterServiceTest.cs
=> removed use of Microsoft.AspNet.WebApi.Client

.github/workflows/build-and-analyze-fork.yml, .github/workflows/build-and-analyze.yml, .github/workflows/use-case-ATX.yaml, test/k6/src/tests/app-events.js, test/k6/src/tests/events.js, test/k6/src/tests/subscriptions.js
Initial workflow for use case tests. Only for AT22 now. Commented out reporting to slack
=> added use case workflow

.github/workflows/use-case-ATX.yaml
- Simplified use case workflow for AT to use matrix strategy. 
- Report to slack per environment that faills. 
- #285
=> Simplified AT use case workflow

src/Events/Controllers/EventsController.cs, src/Events/Repository/CloudEventRepository.cs, src/Events/Services/AuthorizationService.cs, src/Events/Services/EventsService.cs, src/Events/Services/Interfaces/IAuthorization.cs, test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingServices/EventsServiceTest.cs, test/k6/src/api/events.js, test/k6/src/apiHelpers.js, test/k6/src/tests/events/get.js
- Modified k6 test w.r.t how query params are included in request
- Removed required attribute for query params causing issues for APIM
- Updated repository class to handle nullvalue for subject
Still to be fixed: no events returned with getEvents function
- #108
=> Ensuring query params included in request

src/Events/Repository/CloudEventRepository.cs
=> only manipulate time if not null

test/k6/src/tests/events/get.js
=> parse response body in k6

src/Events/Controllers/EventsController.cs, src/Events/Migration/v0.26/01-alter-function.sql, src/Events/Program.cs, src/Events/Repository/CloudEventRepository.cs, src/Events/Repository/ICloudEventRepository.cs, src/Events/Services/EventsService.cs, src/Events/Services/Interfaces/IEventsService.cs, test/Altinn.Platform.Events.Tests/Data/events/3.json, test/Altinn.Platform.Events.Tests/Mocks/CloudEventRepositoryMock.cs, test/Altinn.Platform.Events.Tests/Mocks/EventsServiceMock.cs, test/Altinn.Platform.Events.Tests/Models/EventsTableEntry.cs, test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingServices/EventsServiceTest.cs
- Alternative subject as header
- Source no longer a list, required string.
- Next link composes subject query param if only alternativeSubject header provided
- #108
=> Alternative subject as header

src/Events/Controllers/EventsController.cs, test/k6/src/api/events.js, test/k6/src/tests/events/get.js
Extended test set for get events.
- #108
=> added automated test to verify next url

src/Events/Controllers/EventsController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs
=> limit get events to 1000 events

src/Events/Controllers/InboundController.cs, src/Events/Controllers/OutboundController.cs, src/Events/Controllers/StorageController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/InboundControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingControllers/OutboundControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingControllers/StorageControllerTests.cs
=> only accepting application/cloudevents+json internal endpoints

src/Events.Functions/Altinn.Platform.Events.Functions.csproj, src/Events/Altinn.Platform.Events.csproj
Bump AccessToken and Microsoft.IdentityModel.Tokens.
=> Bump package references

src/Events/Authorization/GenericCloudEventXacmlMapper.cs
=> bug fix: null check for resource

src/Events/Authorization/GenericCloudEventXacmlMapper.cs
This reverts commit 0295b071efeff86609500325d5d89f58d885bc91.
Reverted change, opted to alter bad obsolete testdata instead
=> Revert "bug fix: null check for resource (#334)"

.github/workflows/use-case-TT02.yaml, test/k6/src/api/events.js, test/k6/src/apiHelpers.js, test/k6/src/config.js, test/k6/src/tests/app-events.js, test/k6/src/tests/events/get.js, test/k6/src/tests/events/post.js, test/k6/src/tests/subscriptions.js
- Use case workflow for TT02 including generic event cases
- fixed bug in subscription tests
- try/catch in all test files to ensure all errors not related to test results are identified
=> added use case workflow for tt02

test/k6/src/tests/subscriptions.js
Use case test for subscription also verifies that subscription is validated to ensure that validation function is running ok.
=> check subscription is validated after 15 sec

src/Events/Migration/v0.31/01-drop-function.sql
Removing obsolete functions from database. 
- #315
=> drop obsolete functions

.github/workflows/use-case-ATX.yaml, .github/workflows/use-case-TT02.yaml
=> run all test steps always

src/Events/Altinn.Platform.Events.csproj, src/Events/Program.cs
Added health check towards db to existing health checks.
- N/A
=> Added db check to health checks

src/Events/Controllers/WebhookReceiverController.cs
New endpoint to support automated tests. 
PR for required changes in APIM: https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/668 
as endpoint will require an APIM product for access
- N/A
=> webhook receiver endpoint for testing

src/Events/Controllers/WebhookReceiverController.cs
Test endpoint should accept application/json 
- #N/A
=> pushed content type is json, should accept this

.github/workflows/use-case-ATX.yaml, test/k6/src/data/subscriptions/02-generic-subscription.json, test/k6/src/tests/subscriptions.js
Using new internal endpoint for subscription webhook in k6 tests
- #N/A
=> Extend k6 test for subscription

.github/workflows/use-case-TT02.yaml, test/k6/src/api/webhooksite.js, test/k6/src/tests/subscriptions.js
Cleaned up obsolete code and using updated variables for tt02 workflow
=> Use updated k6 variables in tt02 

.github/workflows/build-and-analyze-fork.yml, .github/workflows/build-and-analyze.yml, .github/workflows/codeql-analysis.yml, Dockerfile, src/Events/Altinn.Platform.Events.csproj, test/Altinn.Platform.Events.Tests/Altinn.Platform.Events.Tests.csproj
=> Patching w24

src/Events/Authorization/AppCloudEventXacmlMapper.cs, src/Events/Configuration/AuthorizationConstants.cs, src/Events/Configuration/PlatformSettings.cs, src/Events/Controllers/SubscriptionController.cs, src/Events/Extensions/AppCloudEventExtensions.cs, src/Events/Services/AppSubscriptionService.cs, test/Altinn.Platform.Events.Tests/TestingExtensions/AppCloudEventExtensionsTests.cs
Mapping from app event to generic event now includes setting extension attributes resource and resourceinstance. 
- #338
=> set resource and resourceinstance for app events

src/Events/Migration/v0.32/02-update-function.sql, src/Events/Migration/v0.33/01-alter-function.sql
=> Added blank test

src/Events/Authorization/GenericCloudEventXacmlMapper.cs, src/Events/Authorization/SubscriptionXacmlMapper.cs, src/Events/Authorization/XacmlMapperHelper.cs, src/Events/Configuration/AuthorizationConstants.cs, src/Events/Services/GenericSubscriptionService.cs, test/Altinn.Platform.Events.Tests/TestingServices/GenericSubscriptionServiceTest.cs, test/Altinn.Platform.Events.Tests/TestingUtils/SubscriptionXacmlMapperTests.cs
Resource authorization on post of generic subscription implemented.
- #259
=> implemented authorization for post generic subscription

src/Events/Migration/v0.34/01-create-function.sql, src/Events/Migration/v0.34/02-new-indexes.sql, src/Events/Repository/ISubscriptionRepository.cs, src/Events/Repository/SubscriptionRepository.cs, src/Events/Repository/SubscriptionRepositoryCachingDecorator.cs, src/Events/Services/OutboundService.cs, src/Events/appsettings.json, test/Altinn.Platform.Events.Tests/Data/subscriptions/1.json, test/Altinn.Platform.Events.Tests/Mocks/SubscriptionRepositoryMock.cs, test/Altinn.Platform.Events.Tests/Models/SubscriptionTableEntry.cs, test/Altinn.Platform.Events.Tests/TestingDecorators/SubscriptionRepositoryCacheDecoratorTest.cs, test/Altinn.Platform.Events.Tests/TestingServices/OutboundServiceTests.cs
- Ensuring lower case on resourcefilter. Will ensure lower case on events in later issue. 
- #370
=> Match subscription to event on resource

src/Events/Program.cs
=> top level annotations for endpoint

src/Events/Services/AppSubscriptionService.cs
No  longer requiring source filter for app subscriptions, but will need to be on valid format if provided, 
- N/A
=> sourcefilter optional for app subscription

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
=> Revert patching of AccessTokenClient

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
=> Comment AccessTokenClient reference

test/k6/src/tests/events/get.js
Should be merged before #403 
- #316
=> updated k6 tests

test/k6/docker-compose.yml
=> patched k6 image

src/Events/Repository/CloudEventRepository.cs
=> bugfix: remove name from pg parameter

src/Events/Migration/v0.36/01-new-indexes.sql
Adding an index on the cloudevent->>'resource' "column" in the events table.
- #316
=> Add index for cloudevent.resource

.github/workflows/use-case-TT02.yaml, test/k6/src/api/authentication.js, test/k6/src/api/maskinporten.js, test/k6/src/api/token-generator.js, test/k6/src/apiHelpers.js, test/k6/src/config.js, test/k6/src/setup.js, test/k6/src/tests/app-events.js, test/k6/src/tests/events/get.js, test/k6/src/tests/events/post.js, test/k6/src/tests/subscriptions.js
=> support for maskinporten and username pw login

test/k6/readme.md, test/k6/src/tests/subscriptions.js
Added missing scope to k6 test to ensure subscription tests run green. "ttd" missing from claims if last scope not added
=> added serviceowner scope

src/Events/Altinn.Platform.Events.csproj
Patched dependency to latest version. 
Can make the transition to data source in a seperate pr if patching is successful
=> AspNetCore.HealthChecks.NpgSql -> v7

.github/workflows/use-case-ATX.yaml
The SSL sertificate for at21 is invalid and I'm note sure if it'll be fixed.
=> Removed env at21

src/Events.Functions/EventsInbound.cs, src/Events.Functions/EventsOutbound.cs, src/Events.Functions/EventsRegistration.cs, src/Events.Functions/SubscriptionValidation.cs, test/Altinn.Platform.Events.Functions.Tests/TestingFunctions/EventRegistrationTests.cs, test/Altinn.Platform.Events.Functions.Tests/TestingFunctions/EventsInboundTests.cs, test/Altinn.Platform.Events.Functions.Tests/TestingFunctions/EventsOutboundTests.cs, test/Altinn.Platform.Events.Functions.Tests/TestingFunctions/SubscriptionValidationTests.cs
Removing an unused input parameter to the Run methods of all functions.
=> Remove unused parameter: log

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
Rolling back AccessTokenClient. Other dependencies are updated.
=> Rollback AccessTokenClient to version 1.1.3

src/Events/Altinn.Platform.Events.csproj, src/Events/Controllers/AppController.cs, src/Events/Controllers/EventsController.cs, src/Events/Exceptions/PlatformHttpException.cs, src/Events/Program.cs
Updating dependencies:
- AccessToken
- AccessTokenClient
- JWTCookieAuthentication
- Patching
=> Bump access token and cookie auth libs

src/Events/Altinn.Platform.Events.csproj
The updated packages doesn't work. Need to do a more systematic test.
=> Rollback dependencies

src/Events/Altinn.Platform.Events.csproj, test/Altinn.Platform.Events.Tests/Altinn.Platform.Events.Tests.csproj
Upgraded PEP and Accesstoken dependencies to latester preview and stable version
=> patched PEP and access token

src/Events/Swagger/RequestBodyExampleFilter.cs, test/Altinn.Platform.Events.Functions.Tests/TestingFunctions/EventsOutboundTests.cs
=> Updated test and example data

src/Events.Functions/Altinn.Platform.Events.Functions.csproj, src/Events.Functions/local.settings.json, test/Altinn.Platform.Events.Functions.Tests/Altinn.Platform.Events.Functions.Tests.csproj, test/k6/src/tests/subscriptions.js
=> Functions running .net 8

src/Events.Functions/Altinn.Platform.Events.Functions.csproj, src/Events.Functions/local.settings.json, test/Altinn.Platform.Events.Functions.Tests/Altinn.Platform.Events.Functions.Tests.csproj, test/k6/src/tests/subscriptions.js
Reverts Altinn/altinn-events#485
=> Revert "Functions running .net 8"

src/Events/Altinn.Platform.Events.csproj
Upgrade of `AccessTokenClient`
Upgrade of `AccessTokenClient`
- https://github.com/Altinn/altinn-accesstoken/issues/50
=> Upgrade of `AccessTokenClient`

src/Events/Configuration/CustomTelemetryInitializer.cs, src/Events/Migration/v0.40/01-create-function.sql, src/Events/Repository/CloudEventRepository.cs
- Changed filter in getappevents_v2
- Disabled sampling
- altinn/altinn-support-private#2733
=> Changed filter in getappevents_v2

src/Events/Swagger/RequestBodyExampleFilter.cs, src/Events/Swagger/SchemaExampleFilter.cs
Updated all resource examples in Swagger filters
=> updated all resource examples

src/Events.Functions/Altinn.Platform.Events.Functions.csproj, src/Events.Functions/Clients/EventsClient.cs, src/Events.Functions/Services/WebhookService.cs, test/Altinn.Platform.Events.Functions.Tests/TestingClients/EventsClientTests.cs, test/Altinn.Platform.Events.Functions.Tests/TestingServices/WebhookServiceTests.cs
Rollback of the dependency updates in Events Functions.
=> Rollback dependency updates

src/Events/Configuration/GeneralSettings.cs, src/Events/Controllers/EventsController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs
Removed config value and all logic related to the feature switch
- #442
=> removed EnableExternalEvents switch

src/Events/Authorization/GenericCloudEventXacmlMapper.cs
Allow traditional subjects in the authorization request for generic events too. 
- #520 
-
=> include traditional subjects in authorization request

.github/workflows/regression-test-AT22.yaml, .github/workflows/regression-test-AT23.yaml, .github/workflows/regression-test-AT24.yaml, .github/workflows/regression-test-ATX.yaml, .github/workflows/regression-test-PROD.yaml, .github/workflows/regression-test-TT02.yaml, .github/workflows/use-case-ATX.yaml, .github/workflows/use-case-PROD.yaml, .github/workflows/use-case-TT02.yaml, test/k6/src/tests/subscriptions.js
Added regression test workflow for all environments
Added use case workflows for production
=> Automated test workflows added

src/Events/Controllers/AppController.cs, src/Events/Controllers/EventsController.cs, test/Altinn.Platform.Events.Tests/TestingControllers/AppControllerTests.cs, test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs
=> Added validation of query parameter combinations

src/Events/Controllers/AppController.cs, test/Altinn.Platform.Events.Tests/Mocks/EventsServiceMock.cs, test/Altinn.Platform.Events.Tests/TestingControllers/AppControllerTests.cs
Bug fix: too broad validation on subject required
- #554
=> validation rule only for getforparty

Dockerfile, src/Events/Altinn.Platform.Events.csproj
=> Update .Net and Json

test/Altinn.Platform.Events.Functions.Tests/Altinn.Platform.Events.Functions.Tests.csproj, test/Altinn.Platform.Events.Tests/Altinn.Platform.Events.Tests.csproj
Dependencies not picked up by renovate
=> Bump test dependencies

src/Events.Functions/Altinn.Platform.Events.Functions.csproj, src/Events/Altinn.Platform.Events.csproj
Reverts Altinn/altinn-events#565
=> Revert "chore(deps): update nuget non-major dependencies"

src/Events.Functions/Altinn.Platform.Events.Functions.csproj
=> patched webjobs packages

src/Events/Controllers/AppController.cs, src/Events/Controllers/StorageController.cs
=> Added logging of id

test/k6/src/tests/subscriptions.js
Ensure test run does not break and stop due to parsing of non existent response body
=> fixed test check order

test/k6/src/tests/events/post.js
Created a new function, `createCloudEvent`, to generate cloud events for testing purposes, ensuring that each event is assigned a unique UUID. Updated the test units to utilize this function for consistent and distinct event identification.
- #571
=> Create a new function to generate unique cloud events

.github/workflows/build-and-analyze.yml
Make test results available as artifact in workflow
=> Upload test results

src/Events/Program.cs
There are currently no traces, metrics or logs from "platform-events". Trying to fix it by moving the service registration to earlier in the process. There is a known issue related to keyed services. If there are any keyed service registration, the registration of application insights will fail, silently.
- #638
=> Move application insights services registration

.github/workflows/regression-test-ATX.yml, .github/workflows/regression-test-PROD.yaml, .github/workflows/regression-test-TT02.yaml, .github/workflows/use-case-ATX.yaml, .github/workflows/use-case-PROD.yaml, .github/workflows/use-case-TT02.yaml
Follow recommendations from docs for Slack github action v2, to adjust to breaking changes
- [# 132 (team-core-private)](https://github.com/Altinn/team-core-private/issues/132)
=>  Fix job that reports failed tests to Slack

src/Events/Program.cs, src/Events/Repository/CloudEventRepository.cs, src/Events/Repository/SubscriptionRepository.cs, src/Events/Repository/TraceLogRepository.cs
Rewrite setup of OTEL npg sql logging. 
Questions - do we not want to log parameters? 
- #https://github.com/Altinn/team-core-private/issues/188
=> Change npgsql logging

test/k6/src/api/authentication.js, test/k6/src/config.js
The original issue was about the use-case tests running from altinn-studio as a Azure DevOps pipeline. I gues we forgot that we have other use-case scripts as well.
- https://github.com/Altinn/altinn-notifications/issues/802
=> Set correct auth cookie name for altinnii
